package hearth.kindlings.parser
package internal.runtime

import scala.collection.mutable.ListBuffer

/** A grammar ready to run: its tables plus the code of its actions and terminal conversions, either generated by the
  * macro ([[GeneratedGrammar]]) or collected from the evaluated grammar block ([[InterpretedGrammar]]).
  */
abstract private[parser] class CompiledGrammar(val tables: Tables) {

  /** The value of user production `p` (`ActPure`: the result, `ActEffect`: the action's `F[R]`), whose right-hand side
    * values are `values(base until base + len)` (terminals as matched text, non-terminals as their values).
    */
  def userAction(p: Int, values: Array[Any], base: Int): Any

  /** The converted value of right-hand side position `i` of production `p` (for built-in actions). */
  def argument(p: Int, i: Int, raw: Any): Any
}
private[parser] object CompiledGrammar {

  final val ActPure = 0
  final val ActEffect = 1
  final val ActPass = 2
  final val ActConst = 3
  final val ActOptNone = 4
  final val ActOptSome = 5
  final val ActListEmpty = 6
  final val ActListOne = 7
  final val ActListAppend = 8

  def listify(value: Any): List[Any] = value.asInstanceOf[ListBuffer[Any]].toList
}

/** A grammar whose reductions (and `String` lexer) are generated by the macro: the machine calls
  * [[GeneratedReductions]] directly, so the per-production interpretation below is never used.
  */
final private[parser] class GeneratedGrammar(tables: Tables, val reductions: GeneratedReductions)
    extends CompiledGrammar(tables) {

  def userAction(p: Int, values: Array[Any], base: Int): Any =
    throw new IllegalStateException("generated grammars reduce with GeneratedReductions.reduce")

  def argument(p: Int, i: Int, raw: Any): Any =
    throw new IllegalStateException("generated grammars reduce with GeneratedReductions.reduce")
}

/** Actions and conversions collected at run time from the evaluated grammar block (see `Grammar.interpreted`). */
final private[parser] class InterpretedGrammar(tables: Tables, flat: Flatten.Result[String => Any, Alt.Action])
    extends CompiledGrammar(tables) {

  private val prodCount = flat.prods.size + 1

  /** Per production and position: `null` for plain values, [[InterpretedGrammar.ListifyMarker]], or a converter. */
  private val converters: Array[Array[Any]] = new Array[Array[Any]](prodCount)
  private val actionFn: Array[Array[Any] => Any] = new Array[Array[Any] => Any](prodCount)

  flat.prods.zipWithIndex.foreach { case (prod, index) =>
    val p = index + 1
    converters(p) = prod.rhs
      .map {
        case Flatten.RNt(_, true)   => InterpretedGrammar.ListifyMarker
        case Flatten.RNt(_, false)  => null
        case Flatten.RTerm(convert) => convert
      }
      .toArray[Any]
    prod.action match {
      case Flatten.AUser(action) => actionFn(p) = action.fn
      case _                     => ()
    }
  }

  def argument(p: Int, i: Int, raw: Any): Any = converters(p)(i) match {
    case null                             => raw
    case InterpretedGrammar.ListifyMarker => CompiledGrammar.listify(raw)
    case convert                          => convert.asInstanceOf[String => Any](raw.asInstanceOf[String])
  }

  def userAction(p: Int, values: Array[Any], base: Int): Any = {
    val len = tables.prodLen(p)
    val args = new Array[Any](len)
    var i = 0
    while (i < len) {
      args(i) = argument(p, i, values(base + i))
      i += 1
    }
    actionFn(p)(args)
  }
}
private[parser] object InterpretedGrammar {
  object ListifyMarker
}
