// Generated by scripts/gen-parser-dsl-sequences.py - do not edit by hand.
package hearth.kindlings.parser

import scala.annotation.compileTimeOnly

/** `all(s1, ..., sN)`: a sequence of symbols, finished with an action: `{ (v1, ..., vN) => F[R] }` (effectful, the
  * default) or `.pure { (v1, ..., vN) => R }`. `.prec(op)` overrides the production's precedence (yacc's `%prec`).
  */
trait DslSequences[F[_]] {

  def all[T1](s1: Sym[T1]): All1[F, T1] = new All1[F, T1](List(s1))
  def all[T1, T2](s1: Sym[T1], s2: Sym[T2]): All2[F, T1, T2] = new All2[F, T1, T2](List(s1, s2))
  def all[T1, T2, T3](s1: Sym[T1], s2: Sym[T2], s3: Sym[T3]): All3[F, T1, T2, T3] =
    new All3[F, T1, T2, T3](List(s1, s2, s3))
  def all[T1, T2, T3, T4](s1: Sym[T1], s2: Sym[T2], s3: Sym[T3], s4: Sym[T4]): All4[F, T1, T2, T3, T4] =
    new All4[F, T1, T2, T3, T4](List(s1, s2, s3, s4))
  def all[T1, T2, T3, T4, T5](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5]
  ): All5[F, T1, T2, T3, T4, T5] = new All5[F, T1, T2, T3, T4, T5](List(s1, s2, s3, s4, s5))
  def all[T1, T2, T3, T4, T5, T6](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6]
  ): All6[F, T1, T2, T3, T4, T5, T6] = new All6[F, T1, T2, T3, T4, T5, T6](List(s1, s2, s3, s4, s5, s6))
  def all[T1, T2, T3, T4, T5, T6, T7](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7]
  ): All7[F, T1, T2, T3, T4, T5, T6, T7] = new All7[F, T1, T2, T3, T4, T5, T6, T7](List(s1, s2, s3, s4, s5, s6, s7))
  def all[T1, T2, T3, T4, T5, T6, T7, T8](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8]
  ): All8[F, T1, T2, T3, T4, T5, T6, T7, T8] =
    new All8[F, T1, T2, T3, T4, T5, T6, T7, T8](List(s1, s2, s3, s4, s5, s6, s7, s8))
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9]
  ): All9[F, T1, T2, T3, T4, T5, T6, T7, T8, T9] =
    new All9[F, T1, T2, T3, T4, T5, T6, T7, T8, T9](List(s1, s2, s3, s4, s5, s6, s7, s8, s9))
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10]
  ): All10[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] =
    new All10[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10))
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11]
  ): All11[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11] =
    new All11[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11](List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11))
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12]
  ): All12[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] =
    new All12[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13]
  ): All13[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13] =
    new All13[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14]
  ): All14[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14] =
    new All14[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14],
      s15: Sym[T15]
  ): All15[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15] =
    new All15[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14],
      s15: Sym[T15],
      s16: Sym[T16]
  ): All16[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16] =
    new All16[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14],
      s15: Sym[T15],
      s16: Sym[T16],
      s17: Sym[T17]
  ): All17[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17] =
    new All17[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14],
      s15: Sym[T15],
      s16: Sym[T16],
      s17: Sym[T17],
      s18: Sym[T18]
  ): All18[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18] =
    new All18[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14],
      s15: Sym[T15],
      s16: Sym[T16],
      s17: Sym[T17],
      s18: Sym[T18],
      s19: Sym[T19]
  ): All19[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19] =
    new All19[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14],
      s15: Sym[T15],
      s16: Sym[T16],
      s17: Sym[T17],
      s18: Sym[T18],
      s19: Sym[T19],
      s20: Sym[T20]
  ): All20[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20] =
    new All20[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14],
      s15: Sym[T15],
      s16: Sym[T16],
      s17: Sym[T17],
      s18: Sym[T18],
      s19: Sym[T19],
      s20: Sym[T20],
      s21: Sym[T21]
  ): All21[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21] =
    new All21[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21)
    )
  def all[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](
      s1: Sym[T1],
      s2: Sym[T2],
      s3: Sym[T3],
      s4: Sym[T4],
      s5: Sym[T5],
      s6: Sym[T6],
      s7: Sym[T7],
      s8: Sym[T8],
      s9: Sym[T9],
      s10: Sym[T10],
      s11: Sym[T11],
      s12: Sym[T12],
      s13: Sym[T13],
      s14: Sym[T14],
      s15: Sym[T15],
      s16: Sym[T16],
      s17: Sym[T17],
      s18: Sym[T18],
      s19: Sym[T19],
      s20: Sym[T20],
      s21: Sym[T21],
      s22: Sym[T22]
  ): All22[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22] =
    new All22[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](
      List(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21, s22)
    )

  /** Sequences are limited to 22 symbols: split longer ones into helper non-terminals or groups. */
  @compileTimeOnly("all(...) takes at most 22 symbols: split the sequence into helper non-terminals or groups")
  def all(syms: Sym[Any]*): AllTooLong = new AllTooLong(syms.toList)
}

final class AllTooLong private[parser] (private[parser] val syms: List[Sym[Any]])

final class All1[F[_], T1] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: T1 => F[R]): Alt[R] =
    Alt.user[R](syms, effectful = true, args => action(args(0).asInstanceOf[T1]))
  def pure[R](action: T1 => R): Alt[R] = Alt.user[R](syms, effectful = false, args => action(args(0).asInstanceOf[T1]))
  def prec(operator: Sym[Any]): All1[F, T1] = { val _ = operator; this }
}

final class All2[F[_], T1, T2] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: (T1, T2) => F[R]): Alt[R] =
    Alt.user[R](syms, effectful = true, args => action(args(0).asInstanceOf[T1], args(1).asInstanceOf[T2]))
  def pure[R](action: (T1, T2) => R): Alt[R] =
    Alt.user[R](syms, effectful = false, args => action(args(0).asInstanceOf[T1], args(1).asInstanceOf[T2]))
  def prec(operator: Sym[Any]): All2[F, T1, T2] = { val _ = operator; this }
}

final class All3[F[_], T1, T2, T3] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: (T1, T2, T3) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args => action(args(0).asInstanceOf[T1], args(1).asInstanceOf[T2], args(2).asInstanceOf[T3])
  )
  def pure[R](action: (T1, T2, T3) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args => action(args(0).asInstanceOf[T1], args(1).asInstanceOf[T2], args(2).asInstanceOf[T3])
  )
  def prec(operator: Sym[Any]): All3[F, T1, T2, T3] = { val _ = operator; this }
}

final class All4[F[_], T1, T2, T3, T4] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: (T1, T2, T3, T4) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(args(0).asInstanceOf[T1], args(1).asInstanceOf[T2], args(2).asInstanceOf[T3], args(3).asInstanceOf[T4])
  )
  def pure[R](action: (T1, T2, T3, T4) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(args(0).asInstanceOf[T1], args(1).asInstanceOf[T2], args(2).asInstanceOf[T3], args(3).asInstanceOf[T4])
  )
  def prec(operator: Sym[Any]): All4[F, T1, T2, T3, T4] = { val _ = operator; this }
}

final class All5[F[_], T1, T2, T3, T4, T5] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: (T1, T2, T3, T4, T5) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5]
      )
  )
  def prec(operator: Sym[Any]): All5[F, T1, T2, T3, T4, T5] = { val _ = operator; this }
}

final class All6[F[_], T1, T2, T3, T4, T5, T6] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6]
      )
  )
  def prec(operator: Sym[Any]): All6[F, T1, T2, T3, T4, T5, T6] = { val _ = operator; this }
}

final class All7[F[_], T1, T2, T3, T4, T5, T6, T7] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7]
      )
  )
  def prec(operator: Sym[Any]): All7[F, T1, T2, T3, T4, T5, T6, T7] = { val _ = operator; this }
}

final class All8[F[_], T1, T2, T3, T4, T5, T6, T7, T8] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8]
      )
  )
  def prec(operator: Sym[Any]): All8[F, T1, T2, T3, T4, T5, T6, T7, T8] = { val _ = operator; this }
}

final class All9[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9]
      )
  )
  def prec(operator: Sym[Any]): All9[F, T1, T2, T3, T4, T5, T6, T7, T8, T9] = { val _ = operator; this }
}

final class All10[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] private[parser] (
    private[parser] val syms: List[Sym[Any]]
) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10]
      )
  )
  def prec(operator: Sym[Any]): All10[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] = { val _ = operator; this }
}

final class All11[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11] private[parser] (
    private[parser] val syms: List[Sym[Any]]
) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11]
      )
  )
  def prec(operator: Sym[Any]): All11[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11] = { val _ = operator; this }
}

final class All12[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] private[parser] (
    private[parser] val syms: List[Sym[Any]]
) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12]
      )
  )
  def prec(operator: Sym[Any]): All12[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] = { val _ = operator; this }
}

final class All13[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13] private[parser] (
    private[parser] val syms: List[Sym[Any]]
) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13]
      )
  )
  def prec(operator: Sym[Any]): All13[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13] = {
    val _ = operator; this
  }
}

final class All14[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14] private[parser] (
    private[parser] val syms: List[Sym[Any]]
) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => F[R]): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14]
      )
  )
  def prec(operator: Sym[Any]): All14[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14] = {
    val _ = operator; this
  }
}

final class All15[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15] private[parser] (
    private[parser] val syms: List[Sym[Any]]
) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => F[R]): Alt[R] =
    Alt.user[R](
      syms,
      effectful = true,
      args =>
        action(
          args(0).asInstanceOf[T1],
          args(1).asInstanceOf[T2],
          args(2).asInstanceOf[T3],
          args(3).asInstanceOf[T4],
          args(4).asInstanceOf[T5],
          args(5).asInstanceOf[T6],
          args(6).asInstanceOf[T7],
          args(7).asInstanceOf[T8],
          args(8).asInstanceOf[T9],
          args(9).asInstanceOf[T10],
          args(10).asInstanceOf[T11],
          args(11).asInstanceOf[T12],
          args(12).asInstanceOf[T13],
          args(13).asInstanceOf[T14],
          args(14).asInstanceOf[T15]
        )
    )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15) => R): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15]
      )
  )
  def prec(operator: Sym[Any]): All15[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15] = {
    val _ = operator; this
  }
}

final class All16[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16] private[parser] (
    private[parser] val syms: List[Sym[Any]]
) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => F[R]): Alt[R] =
    Alt.user[R](
      syms,
      effectful = true,
      args =>
        action(
          args(0).asInstanceOf[T1],
          args(1).asInstanceOf[T2],
          args(2).asInstanceOf[T3],
          args(3).asInstanceOf[T4],
          args(4).asInstanceOf[T5],
          args(5).asInstanceOf[T6],
          args(6).asInstanceOf[T7],
          args(7).asInstanceOf[T8],
          args(8).asInstanceOf[T9],
          args(9).asInstanceOf[T10],
          args(10).asInstanceOf[T11],
          args(11).asInstanceOf[T12],
          args(12).asInstanceOf[T13],
          args(13).asInstanceOf[T14],
          args(14).asInstanceOf[T15],
          args(15).asInstanceOf[T16]
        )
    )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16) => R): Alt[R] =
    Alt.user[R](
      syms,
      effectful = false,
      args =>
        action(
          args(0).asInstanceOf[T1],
          args(1).asInstanceOf[T2],
          args(2).asInstanceOf[T3],
          args(3).asInstanceOf[T4],
          args(4).asInstanceOf[T5],
          args(5).asInstanceOf[T6],
          args(6).asInstanceOf[T7],
          args(7).asInstanceOf[T8],
          args(8).asInstanceOf[T9],
          args(9).asInstanceOf[T10],
          args(10).asInstanceOf[T11],
          args(11).asInstanceOf[T12],
          args(12).asInstanceOf[T13],
          args(13).asInstanceOf[T14],
          args(14).asInstanceOf[T15],
          args(15).asInstanceOf[T16]
        )
    )
  def prec(operator: Sym[Any]): All16[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16] = {
    val _ = operator; this
  }
}

final class All17[F[_], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17] private[parser] (
    private[parser] val syms: List[Sym[Any]]
) {
  def apply[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => F[R]): Alt[R] =
    Alt.user[R](
      syms,
      effectful = true,
      args =>
        action(
          args(0).asInstanceOf[T1],
          args(1).asInstanceOf[T2],
          args(2).asInstanceOf[T3],
          args(3).asInstanceOf[T4],
          args(4).asInstanceOf[T5],
          args(5).asInstanceOf[T6],
          args(6).asInstanceOf[T7],
          args(7).asInstanceOf[T8],
          args(8).asInstanceOf[T9],
          args(9).asInstanceOf[T10],
          args(10).asInstanceOf[T11],
          args(11).asInstanceOf[T12],
          args(12).asInstanceOf[T13],
          args(13).asInstanceOf[T14],
          args(14).asInstanceOf[T15],
          args(15).asInstanceOf[T16],
          args(16).asInstanceOf[T17]
        )
    )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17) => R): Alt[R] =
    Alt.user[R](
      syms,
      effectful = false,
      args =>
        action(
          args(0).asInstanceOf[T1],
          args(1).asInstanceOf[T2],
          args(2).asInstanceOf[T3],
          args(3).asInstanceOf[T4],
          args(4).asInstanceOf[T5],
          args(5).asInstanceOf[T6],
          args(6).asInstanceOf[T7],
          args(7).asInstanceOf[T8],
          args(8).asInstanceOf[T9],
          args(9).asInstanceOf[T10],
          args(10).asInstanceOf[T11],
          args(11).asInstanceOf[T12],
          args(12).asInstanceOf[T13],
          args(13).asInstanceOf[T14],
          args(14).asInstanceOf[T15],
          args(15).asInstanceOf[T16],
          args(16).asInstanceOf[T17]
        )
    )
  def prec(operator: Sym[Any]): All17[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17] = {
    val _ = operator; this
  }
}

final class All18[
    F[_],
    T1,
    T2,
    T3,
    T4,
    T5,
    T6,
    T7,
    T8,
    T9,
    T10,
    T11,
    T12,
    T13,
    T14,
    T15,
    T16,
    T17,
    T18
] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](
      action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => F[R]
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18]
      )
  )
  def pure[R](action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18) => R): Alt[R] =
    Alt.user[R](
      syms,
      effectful = false,
      args =>
        action(
          args(0).asInstanceOf[T1],
          args(1).asInstanceOf[T2],
          args(2).asInstanceOf[T3],
          args(3).asInstanceOf[T4],
          args(4).asInstanceOf[T5],
          args(5).asInstanceOf[T6],
          args(6).asInstanceOf[T7],
          args(7).asInstanceOf[T8],
          args(8).asInstanceOf[T9],
          args(9).asInstanceOf[T10],
          args(10).asInstanceOf[T11],
          args(11).asInstanceOf[T12],
          args(12).asInstanceOf[T13],
          args(13).asInstanceOf[T14],
          args(14).asInstanceOf[T15],
          args(15).asInstanceOf[T16],
          args(16).asInstanceOf[T17],
          args(17).asInstanceOf[T18]
        )
    )
  def prec(
      operator: Sym[Any]
  ): All18[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18] = {
    val _ = operator; this
  }
}

final class All19[
    F[_],
    T1,
    T2,
    T3,
    T4,
    T5,
    T6,
    T7,
    T8,
    T9,
    T10,
    T11,
    T12,
    T13,
    T14,
    T15,
    T16,
    T17,
    T18,
    T19
] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](
      action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => F[R]
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18],
        args(18).asInstanceOf[T19]
      )
  )
  def pure[R](
      action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19) => R
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18],
        args(18).asInstanceOf[T19]
      )
  )
  def prec(
      operator: Sym[Any]
  ): All19[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19] = {
    val _ = operator; this
  }
}

final class All20[
    F[_],
    T1,
    T2,
    T3,
    T4,
    T5,
    T6,
    T7,
    T8,
    T9,
    T10,
    T11,
    T12,
    T13,
    T14,
    T15,
    T16,
    T17,
    T18,
    T19,
    T20
] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](
      action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => F[R]
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18],
        args(18).asInstanceOf[T19],
        args(19).asInstanceOf[T20]
      )
  )
  def pure[R](
      action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20) => R
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18],
        args(18).asInstanceOf[T19],
        args(19).asInstanceOf[T20]
      )
  )
  def prec(
      operator: Sym[Any]
  ): All20[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20] = {
    val _ = operator; this
  }
}

final class All21[
    F[_],
    T1,
    T2,
    T3,
    T4,
    T5,
    T6,
    T7,
    T8,
    T9,
    T10,
    T11,
    T12,
    T13,
    T14,
    T15,
    T16,
    T17,
    T18,
    T19,
    T20,
    T21
] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](
      action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => F[R]
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18],
        args(18).asInstanceOf[T19],
        args(19).asInstanceOf[T20],
        args(20).asInstanceOf[T21]
      )
  )
  def pure[R](
      action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21) => R
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18],
        args(18).asInstanceOf[T19],
        args(19).asInstanceOf[T20],
        args(20).asInstanceOf[T21]
      )
  )
  def prec(
      operator: Sym[Any]
  ): All21[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21] = {
    val _ = operator; this
  }
}

final class All22[
    F[_],
    T1,
    T2,
    T3,
    T4,
    T5,
    T6,
    T7,
    T8,
    T9,
    T10,
    T11,
    T12,
    T13,
    T14,
    T15,
    T16,
    T17,
    T18,
    T19,
    T20,
    T21,
    T22
] private[parser] (private[parser] val syms: List[Sym[Any]]) {
  def apply[R](
      action: (
          T1,
          T2,
          T3,
          T4,
          T5,
          T6,
          T7,
          T8,
          T9,
          T10,
          T11,
          T12,
          T13,
          T14,
          T15,
          T16,
          T17,
          T18,
          T19,
          T20,
          T21,
          T22
      ) => F[R]
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = true,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18],
        args(18).asInstanceOf[T19],
        args(19).asInstanceOf[T20],
        args(20).asInstanceOf[T21],
        args(21).asInstanceOf[T22]
      )
  )
  def pure[R](
      action: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) => R
  ): Alt[R] = Alt.user[R](
    syms,
    effectful = false,
    args =>
      action(
        args(0).asInstanceOf[T1],
        args(1).asInstanceOf[T2],
        args(2).asInstanceOf[T3],
        args(3).asInstanceOf[T4],
        args(4).asInstanceOf[T5],
        args(5).asInstanceOf[T6],
        args(6).asInstanceOf[T7],
        args(7).asInstanceOf[T8],
        args(8).asInstanceOf[T9],
        args(9).asInstanceOf[T10],
        args(10).asInstanceOf[T11],
        args(11).asInstanceOf[T12],
        args(12).asInstanceOf[T13],
        args(13).asInstanceOf[T14],
        args(14).asInstanceOf[T15],
        args(15).asInstanceOf[T16],
        args(16).asInstanceOf[T17],
        args(17).asInstanceOf[T18],
        args(18).asInstanceOf[T19],
        args(19).asInstanceOf[T20],
        args(20).asInstanceOf[T21],
        args(21).asInstanceOf[T22]
      )
  )
  def prec(
      operator: Sym[Any]
  ): All22[F, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22] = {
    val _ = operator; this
  }
}
