package hearth.kindlings.pureconfigderivation

import pureconfig.ConfigReader

/** A subtype of [[pureconfig.ConfigReader]] that is generated by the kindlings macros.
  *
  * Extending the upstream `pureconfig.ConfigReader` (rather than wrapping it) means a derived instance can be used
  * wherever a `ConfigReader` is expected — including with `pureconfig.ConfigSource.string("...").load[A]` from regular
  * pureconfig user code.
  */
trait KindlingsConfigReader[A] extends ConfigReader[A]
object KindlingsConfigReader extends KindlingsConfigReaderCompanionCompat {

  /** Special type — if its implicit is in scope then macros will log the derivation process.
    *
    * @see
    *   [[hearth.kindlings.pureconfigderivation.debug.logDerivationForKindlingsConfigReader]] for details
    */
  sealed trait LogDerivation
  object LogDerivation extends LogDerivation
}
