package hearth.kindlings.pureconfigderivation

import pureconfig.ConfigConvert

/** A subtype of [[pureconfig.ConfigConvert]] that is generated by the kindlings macros.
  *
  * See [[KindlingsConfigReader]] for the rationale behind extending the upstream type
  * rather than wrapping it.
  */
trait KindlingsConfigConvert[A] extends ConfigConvert[A]
object KindlingsConfigConvert extends KindlingsConfigConvertCompanionCompat {

  /** Special type — if its implicit is in scope then macros will log the derivation process.
    *
    * @see
    *   [[hearth.kindlings.pureconfigderivation.debug.logDerivationForKindlingsConfigReader]] and
    *   [[hearth.kindlings.pureconfigderivation.debug.logDerivationForKindlingsConfigWriter]] for details
    */
  sealed trait LogDerivation
  object LogDerivation extends LogDerivation
}
