package hearth.kindlings.pureconfigderivation

import pureconfig.ConfigWriter

/** A subtype of [[pureconfig.ConfigWriter]] that is generated by the kindlings macros.
  *
  * See [[KindlingsConfigReader]] for the rationale behind extending the upstream type
  * rather than wrapping it.
  */
trait KindlingsConfigWriter[A] extends ConfigWriter[A]
object KindlingsConfigWriter extends KindlingsConfigWriterCompanionCompat {

  /** Special type — if its implicit is in scope then macros will log the derivation process.
    *
    * @see
    *   [[hearth.kindlings.pureconfigderivation.debug.logDerivationForKindlingsConfigWriter]] for details
    */
  sealed trait LogDerivation
  object LogDerivation extends LogDerivation
}
