package hearth.kindlings.newtypeintegration.internal.compiletime

import hearth.{MacroCommons, MacroCommonsScala3}

/** Scala 3 structural matcher for the `@newtype` expansion generated by the scala-newtype-compat compiler plugin: see
  * [[IsValueTypeProviderForNewtype]].
  */
private[compiletime] object NewtypeReprPlatform {

  /** If `tpe` is `Foo.Type[Args]` of a `@newtype`/`@newsubtype` companion `Foo`, returns `Foo.Repr[Args]`. */
  def reprOf(ctx: MacroCommons)(tpe: ctx.UntypedType): Option[ctx.UntypedType] = ctx match {
    case ctx3: MacroCommonsScala3 =>
      import ctx3.quotes.reflect.*

      val (tycon, args) = tpe.asInstanceOf[TypeRepr].dealias match {
        case AppliedType(tycon, args) => (tycon, args)
        case other                    => (other, Nil)
      }
      tycon match {
        case typeRef: TypeRef
            if typeRef.name == "Type" && !typeRef.typeSymbol.flags.is(Flags.Opaque) &&
              typeRef.typeSymbol.flags.is(Flags.Deferred) && typeRef.qualifier.termSymbol.flags.is(Flags.Module) =>
          val prefix = typeRef.qualifier
          val companion = prefix.typeSymbol
          val repr = companion.typeMember("Repr")
          val base = companion.typeMember("Base")
          val tag = companion.typeMember("Tag")
          if (repr.isNoSymbol || base.isNoSymbol || tag.isNoSymbol || !tag.isClassDef) None
          else {
            val reprRef = prefix.select(repr)
            val applied = if (args.isEmpty) reprRef else reprRef.appliedTo(args)
            Some(applied.dealias.simplified.asInstanceOf[ctx.UntypedType])
          }
        case _ => None
      }
    case _ => None
  }
}
