// Generated by scripts/gen-parser-dsl-sequence-tests.py - do not edit by hand.
package hearth.kindlings.parser

final class SequenceAritySpec extends hearth.MacroSuite {
  test("arity 1 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num).prec("+").pure((a1) => List(a1))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num).prec("+")((a1) => Some(List(a1)))
      start
    }
    val expected = (1 to 1).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 2 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num).prec("+").pure((a1, a2) => List(a1, a2))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num).prec("+")((a1, a2) => Some(List(a1, a2)))
      start
    }
    val expected = (1 to 2).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 3 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num).prec("+").pure((a1, a2, a3) => List(a1, a2, a3))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num).prec("+")((a1, a2, a3) => Some(List(a1, a2, a3)))
      start
    }
    val expected = (1 to 3).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 4 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num).prec("+").pure((a1, a2, a3, a4) => List(a1, a2, a3, a4))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num).prec("+")((a1, a2, a3, a4) => Some(List(a1, a2, a3, a4)))
      start
    }
    val expected = (1 to 4).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 5 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num).prec("+").pure((a1, a2, a3, a4, a5) => List(a1, a2, a3, a4, a5))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num).prec("+")((a1, a2, a3, a4, a5) => Some(List(a1, a2, a3, a4, a5)))
      start
    }
    val expected = (1 to 5).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 6 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6) => List(a1, a2, a3, a4, a5, a6))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num).prec("+")((a1, a2, a3, a4, a5, a6) =>
        Some(List(a1, a2, a3, a4, a5, a6))
      )
      start
    }
    val expected = (1 to 6).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 7 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7) => List(a1, a2, a3, a4, a5, a6, a7))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num).prec("+")((a1, a2, a3, a4, a5, a6, a7) =>
        Some(List(a1, a2, a3, a4, a5, a6, a7))
      )
      start
    }
    val expected = (1 to 7).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 8 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8) => List(a1, a2, a3, a4, a5, a6, a7, a8))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num).prec("+")((a1, a2, a3, a4, a5, a6, a7, a8) =>
        Some(List(a1, a2, a3, a4, a5, a6, a7, a8))
      )
      start
    }
    val expected = (1 to 8).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 9 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9) => List(a1, a2, a3, a4, a5, a6, a7, a8, a9))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num).prec("+")((a1, a2, a3, a4, a5, a6, a7, a8, a9) =>
        Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9))
      )
      start
    }
    val expected = (1 to 9).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 10 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) => List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) => Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10))
      )
      start
    }
    val expected = (1 to 10).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 11 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11) => List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11))
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11) => Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11))
      )
      start
    }
    val expected = (1 to 11).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 12 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12) =>
          Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12))
      )
      start
    }
    val expected = (1 to 12).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 13 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13) =>
          Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13))
      )
      start
    }
    val expected = (1 to 13).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 14 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14) =>
          Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14))
      )
      start
    }
    val expected = (1 to 14).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 15 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15) =>
          Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15))
      )
      start
    }
    val expected = (1 to 15).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 16 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16) =>
          Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16))
      )
      start
    }
    val expected = (1 to 16).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 17 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17) =>
          Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17))
      )
      start
    }
    val expected = (1 to 17).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 18 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18) =>
          Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18))
      )
      start
    }
    val expected = (1 to 18).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 19 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num).prec(
        "+"
      )((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19) =>
        Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19))
      )
      start
    }
    val expected = (1 to 19).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 20 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num)
        .prec("+")((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20) =>
          Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20))
        )
      start
    }
    val expected = (1 to 20).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 21 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num
      ).prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num
      ).prec("+")((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21) =>
        Some(List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21))
      )
      start
    }
    val expected = (1 to 21).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

  test("arity 22 preserves argument order for pure and effectful actions") {
    val pure = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num
      ).prec("+")
        .pure((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22) =>
          List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22)
        )
      start
    }
    val effectful = Grammar.interpreted[List[Int], Option] { g =>
      import g.*
      val start = nonTerminal[List[Int]]
      val num = terminal("[0-9]+").map(_.toInt)
      skip(" +")
      left("+")
      start ::= all(
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num,
        num
      ).prec("+")(
        (a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22) =>
          Some(
            List(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22)
          )
      )
      start
    }
    val expected = (1 to 22).toList
    val input = expected.mkString(" ")
    assertEquals(pure.parse(input), Some(expected))
    assertEquals(effectful.parse(input), Some(expected))
    assertEquals(pure.parse(input + " x"), None)
    assertEquals(effectful.parse(input + " x"), None)
  }

}
