#!/usr/bin/env python3
"""Generate end-to-end tests of all public sequence arities, then run scalafmt on the output.

These tests exercise the interpreted grammar's runtime builders, which generated grammars
otherwise erase. Distinct input values verify argument ordering for pure and effectful actions.
"""

from pathlib import Path

OUT = Path("parser/src/test/scala/hearth/kindlings/parser/SequenceAritySpec.scala")
lines = [
    "// Generated by scripts/gen-parser-dsl-sequence-tests.py - do not edit by hand.",
    "package hearth.kindlings.parser",
    "",
    "final class SequenceAritySpec extends hearth.MacroSuite {",
]
for arity in range(1, 23):
    symbols = ", ".join("num" for _ in range(arity))
    args = ", ".join(f"a{i}" for i in range(1, arity + 1))
    lines += [f'  test("arity {arity} preserves argument order for pure and effectful actions") {{']
    for mode in ("pure", "effectful"):
        action = f".pure(({args}) => List({args}))" if mode == "pure" else f"(({args}) => Some(List({args})))"
        lines += [
            f"    val {mode} = Grammar.interpreted[List[Int], Option] {{ g =>",
            "      import g.*",
            "      val start = nonTerminal[List[Int]]",
            '      val num = terminal("[0-9]+").map(_.toInt)',
            '      skip(" +")',
            '      left("+")',
            f'      start ::= all({symbols}).prec("+"){action}',
            "      start",
            "    }",
        ]
    lines += [
        f"    val expected = (1 to {arity}).toList",
        '    val input = expected.mkString(" ")',
        "    assertEquals(pure.parse(input), Some(expected))",
        "    assertEquals(effectful.parse(input), Some(expected))",
        '    assertEquals(pure.parse(input + " x"), None)',
        '    assertEquals(effectful.parse(input + " x"), None)',
        "  }",
        "",
    ]
lines += ["}", ""]
OUT.write_text("\n".join(lines))
