#!/usr/bin/env python3
"""Generates parser/src/main/scala/hearth/kindlings/parser/DslSequences.scala (the `all(...)` builders, arities 1-22).

Run from the repository root, then format with scalafmt:

    python3 scripts/gen-parser-dsl-sequences.py && scalafmt parser/src/main/scala/hearth/kindlings/parser/DslSequences.scala
"""

MAX = 22
OUT = "parser/src/main/scala/hearth/kindlings/parser/DslSequences.scala"

lines = [
    "// Generated by scripts/gen-parser-dsl-sequences.py - do not edit by hand.",
    "package hearth.kindlings.parser",
    "",
    "import scala.annotation.compileTimeOnly",
    "",
    "/** `all(s1, ..., sN)`: a sequence of symbols, finished with an action: `{ (v1, ..., vN) => F[R] }` (effectful, the",
    "  * default) or `.pure { (v1, ..., vN) => R }`. `.prec(op)` overrides the production's precedence (yacc's `%prec`).",
    "  */",
    "trait DslSequences[F[_]] {",
    "",
]
for n in range(1, MAX + 1):
    tp = ", ".join(f"T{k}" for k in range(1, n + 1))
    args = ", ".join(f"s{k}: Sym[T{k}]" for k in range(1, n + 1))
    lst = ", ".join(f"s{k}" for k in range(1, n + 1))
    lines.append(f"  def all[{tp}]({args}): All{n}[F, {tp}] = new All{n}[F, {tp}](List({lst}))")
lines += [
    "",
    f"  /** Sequences are limited to {MAX} symbols: split longer ones into helper non-terminals or groups. */",
    f'  @compileTimeOnly("all(...) takes at most {MAX} symbols: split the sequence into helper non-terminals or groups")',
    "  def all(syms: Sym[Any]*): AllTooLong = new AllTooLong(syms.toList)",
    "}",
    "",
    "final class AllTooLong private[parser] (private[parser] val syms: List[Sym[Any]])",
    "",
]
for n in range(1, MAX + 1):
    tp = ", ".join(f"T{k}" for k in range(1, n + 1))
    ftp = f"({tp})" if n > 1 else "T1"
    call = ", ".join(f"args({k - 1}).asInstanceOf[T{k}]" for k in range(1, n + 1))
    lines += [
        f"final class All{n}[F[_], {tp}] private[parser] (private[parser] val syms: List[Sym[Any]]) {{",
        f"  def apply[R](action: {ftp} => F[R]): Alt[R] = Alt.user[R](syms, effectful = true, args => action({call}))",
        f"  def pure[R](action: {ftp} => R): Alt[R] = Alt.user[R](syms, effectful = false, args => action({call}))",
        f"  def prec(operator: Sym[Any]): All{n}[F, {tp}] = {{ val _ = operator; this }}",
        "}",
        "",
    ]

with open(OUT, "w") as f:
    f.write("\n".join(lines))
